<?php
echo "WASSAP MABROO<br>";
echo "SELAMAT DATANG DI PERTEMUAN";
echo "BERIKUT ADALAH CONTOH KODE PHP SEDERHANA";
echo "YANG MENGGUNAKAN FILE JSON SEBAGAI MEDIA PENYIMPANAN DATA SEMENTARA";
echo "DATA YANG DISIMPAN TIDAK AKAN PERMANEN, BISA HILANG KETIKA SERVER DIMATIKAN";
